name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  types:
    uses: spuxx1701/ci-cd/.github/workflows/npm_types.yml@v1.2

  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v1.2

  test:
    uses: spuxx1701/ci-cd/.github/workflows/npm_test-coverage.yml@v1.2
